apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  
spec:
  replicas: 2 # Number of replicas
  selector:
    matchLabels: 
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice-container
          image: ghcr.io/marwantamermo/solar-system:latest
          ports:
            - containerPort: 3000